# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.21.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
      - run:
          name: Build Docker Image
          command: docker build -t jabok123458/rso-infor:${CIRCLE_SHA1} .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push jabok123458/rso-infor:${CIRCLE_SHA1}
      - run:
          name: Update Helm Chart
          command: |
            git clone git@github.com:RSO-project-Prepih/kubernetis-GKE.git
            cd kubernetis-GKE/img-info-service
            echo "Before sed command:"
            cat ./values.yaml
            sed -i 's|tag: .*|tag: '${CIRCLE_SHA1}'|' ./values.yaml
            echo "After sed command:"
            cat ./values.yaml
            git config user.name "lovc21"
            git config user.email "jakob.dekleva@gmail.com"
            git add ./values.yaml
            git commit -am "Update image tag to ${CIRCLE_SHA1}" || echo "No changes to commit"
            git push origin main
            
            
workflows:
  sample:
    jobs:
      - build